name: CI

on: [push]

env:
  ENV1: true
# ENV2: # undefined 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest] # macos-latest,

    steps:
    - name: Dump Environment
      run:  env | sort

    - name: Test1
      if: ${{ env.ENV1 }} 
      run:  echo Test1

    - name: Test1.1
      if: ${{ ! env.ENV1 }} 
      run:  echo Test1.1

    - name: Test2
      if: env.ENV1
      run:  echo Test2

# Invalid on github
#    - name: Test2.1
#      if: ! env.ENV1
#      run:  echo Test2.1

    - name: Test3
      if: ${{ env.ENV2 }} 
      run:  echo Test3

    - name: Test3.1
      if: ${{ ! env.ENV2 }} 
      run:  echo Test3.1

    - name: Test4
      if: env.ENV2
      run:  echo Test4
